### ISSUE TITLE
BSOD WIN11 21H2 22000.376

### ISSUE THREAD

**Issue by Jorgi3** [TheCruZ/kdmapper#47] opened 2021-12-29 20:01 UTC
loading helloworld.sys causing BSOD

**Comment by S0PEX** [comment] 2022-01-01 16:04
Would you mind posting the BSOD dump?
I just tested the example driver with the latest version of kdmapper and can't reproduce the error.

**Comment by TheCruZ** [comment] 2022-01-03 21:10
I'm not able to reproduce the issue

**Comment by xxTree** [comment] 2022-01-08 02:22
BSOD WIN10 21H2 19044.1415
[010822-6750-01.txt](https://github.com/TheCruZ/kdmapper/files/7832431/010822-6750-01.txt)
txt --> dmp

**Comment by TheCruZ** [comment] 2022-01-09 22:15
> 

Sorry but this BSOD isn't related to this issue since the OP is speaking about Windows 11 BSOD, also your BSOD is Bug Check 0x109 CRITICAL_STRUCTURE_CORRUPTION which probably related to your loaded driver and not to kdmapper since this is so specific BSOD

I will close the issue since I can not reproduce it

**Closed by TheCruZ** 2022-01-09 22:15 UTC

**Comment by winsoning** [comment] 2025-02-12 10:06
Open Kernel Isolation   load Helloworld.sys  bsod
